#!/usr/bin/env bash
# This script starts, stops and restarts process script

if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    kill "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
